### ISSUE TITLE
Binaries in git, forks don't support Git LFS

### ISSUE THREAD

**Issue by antgel** [apehex/jekyll-theme-consulting#3]
In my fork, I tried to add images via LFS, to make the repo smaller. However I got the error:

> `can not upload new objects to public fork`

This is described in https://github.com/git-lfs/git-lfs/issues/1449. Please consider implementing git-lfs, thanks.

**Comment by apehex** [comment]
Hi Antony,

I think you're confusing the theme with your website.

The theme is not intended to host large files, it is only light js / yml / css / html code files.
There are a few images / webfonts indeed but that's 5 Mo in total.
What's more the images (other than the lightweight svg) are supposed to be replaced in your website.

All of the content specifically on top of the theme, specifically made for your own website is supposed to go in ANOTHER repository.
NOT a fork, but another folder (made by "jekyll new" for example as per their docs) that you would setup to use the theme gem. 
Here you can do whatever and post your binary / large files if you want.
Also git-lfs is a system wide installation, really nothing to do with the bundled content.

So NO, git -lfs won't be added here, as long as we strive for clean and optimized code there is no reason.
